package mili

/*
#include "mili.h"
*/
import "C"

import "fmt"

// The three kinds of key are three distinct named types, and that is the whole point
// of naming them.
//
// A sealing key and a symmetric key are both 32 bytes, so a function that took a key
// and guessed its kind from its length would read a symmetric key as a sealing key
// and hand back 32 bytes the caller would then encrypt with, believing they were a
// seed. That is not a runtime error; it is a key used as the wrong kind of key, and
// nothing downstream would notice. Naming the types makes it a compile error instead,
// which is the same rule mili-core applies with `SealingKey` and `SigningKey` and the
// same rule its README states.
type (
	// SealingKey is an X-Wing sealing key: a 32 byte seed for ML-KEM-768 and
	// X25519. The secret half of the sealed box.
	SealingKey []byte

	// SigningKey is a composite signing key: a 64 byte seed, 32 for each of the two
	// component schemes.
	SigningKey []byte

	// SymmetricKey is a 256 bit key. mili has no public operation that consumes one;
	// see [GenerateSymmetricKey].
	SymmetricKey []byte
)

// The key sizes, as bytes.
const (
	// SealingKeySize is the length of a [SealingKey].
	SealingKeySize = 32
	// SigningKeySize is the length of a [SigningKey].
	SigningKeySize = 64
	// SymmetricKeySize is the length of a [SymmetricKey].
	SymmetricKeySize = 32
)

// GenerateSealingKey draws a new X-Wing sealing key from the operating system CSPRNG.
//
// The returned bytes are the private key. See the package documentation for what
// that means for memory: Go's garbage collector will copy them and nothing will zero
// them.
func GenerateSealingKey() (SealingKey, error) {
	out := make([]byte, SealingKeySize)
	var written C.size_t
	code := C.mili_sealing_key_generate((*C.uint8_t)(unsafePointer(out)), C.size_t(len(out)), &written)
	result, err := deliver(code, out, written)
	if err != nil {
		return nil, err
	}
	return SealingKey(result), nil
}

// GenerateSigningKey draws a new composite signing key from the operating system
// CSPRNG.
//
// Every key mili can generate is generated by the library rather than by the caller,
// so the raw bytes exist nowhere but inside it on their way out. That is also why
// there is no "give me 64 random bytes" call on this boundary: a caller that wanted
// that would use crypto/rand directly, and it would not be a mili key.
//
// mili signs deterministically, so a signature does not carry a second nonce. See
// THREAT_MODEL.md section 3.6 for what that does and does not mean.
func GenerateSigningKey() (SigningKey, error) {
	out := make([]byte, SigningKeySize)
	var written C.size_t
	code := C.mili_signing_key_generate((*C.uint8_t)(unsafePointer(out)), C.size_t(len(out)), &written)
	result, err := deliver(code, out, written)
	if err != nil {
		return nil, err
	}
	return SigningKey(result), nil
}

// GenerateSymmetricKey draws a new symmetric key from the operating system CSPRNG.
//
// mili has no public operation that consumes a symmetric key: no format in SPEC.md
// takes one, because every format derives its own key from a seed or from a password.
// A key from here is for a caller's own use, and the honest statement is that this
// library does not hand you anything to use it with. A [Backup] will store and return
// one, which makes it recoverable and still not usable.
//
// SPEC.md section 12.0 records that as a decision rather than an oversight, along
// with the two alternatives that were rejected.
func GenerateSymmetricKey() (SymmetricKey, error) {
	out := make([]byte, SymmetricKeySize)
	var written C.size_t
	code := C.mili_symmetric_key_generate((*C.uint8_t)(unsafePointer(out)), C.size_t(len(out)), &written)
	result, err := deliver(code, out, written)
	if err != nil {
		return nil, err
	}
	return SymmetricKey(result), nil
}

// EncapsulationKey derives the public key for a sealing key.
//
// A public key is not secret. It is still 1216 bytes of ML-KEM-768 plus X25519, and
// deriving it is expensive relative to sealing, so a program that seals repeatedly
// should derive it once.
func EncapsulationKey(seed SealingKey) ([]byte, error) {
	if len(seed) != SealingKeySize {
		return nil, fmt.Errorf("mili: a sealing key is %d bytes, got %d", SealingKeySize, len(seed))
	}
	out := make([]byte, EncapsulationKeySize)
	var written C.size_t
	code := C.mili_encapsulation_key_from_seed(
		(*C.uint8_t)(unsafePointer(seed)),
		(*C.uint8_t)(unsafePointer(out)),
		C.size_t(len(out)),
		&written,
	)
	return deliver(code, out, written)
}

// VerifyingKey derives the public key for a signing key.
//
// mili does not authenticate a public key. A substituted verifying key means a
// substituted signature, and this library will verify it. See THREAT_MODEL.md
// section 5.8.
func VerifyingKey(seed SigningKey) ([]byte, error) {
	if len(seed) != SigningKeySize {
		return nil, fmt.Errorf("mili: a signing key is %d bytes, got %d", SigningKeySize, len(seed))
	}
	out := make([]byte, VerifyingKeySize)
	var written C.size_t
	code := C.mili_verifying_key_from_seed(
		(*C.uint8_t)(unsafePointer(seed)),
		(*C.uint8_t)(unsafePointer(out)),
		C.size_t(len(out)),
		&written,
	)
	return deliver(code, out, written)
}
