/* mili — the C ABI.
 *
 * Hand written and committed, not generated by cbindgen. A generated header is a
 * build artefact that drifts: the generator's version, its configuration and the
 * toolchain all become part of what a caller compiles against, and `SPEC.md`
 * section 16 says a build here is reproducible from the repository alone. A header
 * a person wrote and a person reviews is the version of that idea that a security
 * boundary deserves.
 *
 * The consequence is that this file is checked against `src/lib.rs` by
 * `tests/header.rs`, which reads both and fails if an exported function is missing
 * here or if a signature disagrees. That test is the reason a hand written header is
 * safe to keep.
 *
 * Rules, which `src/lib.rs` states at length and this header repeats because a C
 * caller should not have to open a Rust file to learn them:
 *
 *   - Every length is a `size_t`. Nothing is inferred from a buffer's contents.
 *   - Output buffers belong to the caller. No function here allocates memory the
 *     caller has to free, and none returns a pointer into the library.
 *   - Every function returns an `int32_t`. Zero is success. Null is never used to
 *     report failure.
 *   - Every function that writes anything takes the caller's capacity and writes the
 *     length it used through the last argument. Nothing here trusts the caller to
 *     have allocated what the documentation says, and nothing trusts a size constant
 *     to match what will actually be written: a composite signature is 3379 bytes,
 *     not the 3373 its payload is, and a caller that got that wrong would have been
 *     written past.
 *   - A panic cannot cross this boundary.
 *   - Nothing here is configurable. One suite per format version.
 *
 * Sizes are reported by functions rather than written here as macros, so that a
 * caller compiled against one version of this header and linked against another asks
 * the linked library instead of trusting a constant it baked in.
 */

#ifndef MILI_H
#define MILI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Error codes. Zero is success; every other value is a failure. */
#define MILI_OK 0
#define MILI_FAILED 1
#define MILI_UNSUPPORTED_VERSION 2
#define MILI_INTERNAL 3
#define MILI_IO 4
#define MILI_BUFFER_TOO_SMALL 5

/* Key file and backup payload types, as SPEC.md sections 7 and 8 write them. */
#define MILI_PAYLOAD_SEALING 1
#define MILI_PAYLOAD_SIGNING 2
#define MILI_PAYLOAD_SYMMETRIC 3

/* Sizes. Each writes one `size_t` and returns one of the codes above. */
int32_t mili_sealing_key_size(size_t *out);
int32_t mili_encapsulation_key_size(size_t *out);
int32_t mili_signing_key_size(size_t *out);
int32_t mili_verifying_key_size(size_t *out);
int32_t mili_signature_size(size_t *out);
int32_t mili_symmetric_key_size(size_t *out);
int32_t mili_sealed_box_overhead(size_t *out);
int32_t mili_stream_overhead(size_t plaintext_len, size_t *out);

/* Key generation. Every key mili can generate is generated here rather than by the
 * caller, so that the bytes never exist anywhere but inside the library on their way
 * out. */
int32_t mili_sealing_key_generate(uint8_t *out, size_t capacity, size_t *out_len);
int32_t mili_signing_key_generate(uint8_t *out, size_t capacity, size_t *out_len);
int32_t mili_symmetric_key_generate(uint8_t *out, size_t capacity, size_t *out_len);
int32_t mili_encapsulation_key_from_seed(const uint8_t *seed,
                                         uint8_t *out, size_t capacity, size_t *out_len);

/* The sealed box. `out` must hold plaintext_len + mili_sealed_box_overhead(). */
int32_t mili_seal(const uint8_t *recipient, size_t recipient_len,
                  const uint8_t *plaintext, size_t plaintext_len,
                  uint8_t *out, size_t capacity, size_t *out_len);

/* Opens a sealed box with the first candidate that works. `keys` is `key_count`
 * entries back to back and `keys_len` is `key_count` lengths. A sealed box names no
 * recipient, so a caller with several keys passes them all. */
int32_t mili_open(const uint8_t *sealed, size_t sealed_len,
                  const uint8_t *keys, const size_t *keys_len, size_t key_count,
                  uint8_t *out, size_t capacity, size_t *out_len);

/* Composite signatures. A signature is valid only if both components verify, as
 * SPEC.md section 6 requires. `out` must hold mili_signature_size() bytes, which is
 * 3379: the two component signatures and mili's own six byte header. */
int32_t mili_sign(const uint8_t *seed,
                  const uint8_t *message, size_t message_len,
                  uint8_t *out, size_t capacity, size_t *out_len);
int32_t mili_verify(const uint8_t *verifying,
                    const uint8_t *message, size_t message_len,
                    const uint8_t *signature, size_t signature_len);
int32_t mili_verifying_key_from_seed(const uint8_t *seed,
                                     uint8_t *out, size_t capacity, size_t *out_len);

/* Streams. `out` must hold plaintext_len + mili_stream_overhead(plaintext_len). */
int32_t mili_seal_stream(const uint8_t *key,
                         const uint8_t *plaintext, size_t plaintext_len,
                         uint8_t *out, size_t capacity, size_t *out_len);

/* `maximum_plaintext_len` is the caller's bound on how much plaintext it will
 * accept from a file it does not trust. A stream is not otherwise bounded: see
 * THREAT_MODEL.md section 5.7. */
int32_t mili_open_stream(const uint8_t *stream, size_t stream_len,
                         const uint8_t *keys, const size_t *keys_len, size_t key_count,
                         size_t maximum_plaintext_len,
                         uint8_t *out, size_t capacity, size_t *out_len);

/* Key files. `out` must hold the key length plus 57: a 41 byte header and a 16 byte
 * tag, as SPEC.md section 7 defines. */
int32_t mili_key_file_wrap_sealing(const uint8_t *seed,
                                   const uint8_t *password, size_t password_len,
                                   uint8_t *out, size_t capacity, size_t *out_len);
int32_t mili_key_file_wrap_signing(const uint8_t *seed,
                                   const uint8_t *password, size_t password_len,
                                   uint8_t *out, size_t capacity, size_t *out_len);
int32_t mili_key_file_wrap_symmetric(const uint8_t *seed,
                                     const uint8_t *password, size_t password_len,
                                     uint8_t *out, size_t capacity, size_t *out_len);

/* Opens a key file, stating which kind of key the caller expects: MILI_PAYLOAD_SEALING,
 * MILI_PAYLOAD_SIGNING or MILI_PAYLOAD_SYMMETRIC.
 *
 * The expectation is an argument rather than something inferred from the output
 * buffer. A signing key file asked for as a sealing key produces 64 bytes where a
 * caller allocated 32, and a sealing key file asked for as a signing key produces 32
 * where it allocated 64: the second is a key used as the wrong kind of key, and only
 * the caller's own length check would have caught it.
 *
 * A payload type other than `expected` fails with MILI_FAILED, the same as a wrong
 * password. `out` must hold the key's own size, as mili_signing_key_size and its
 * siblings report. */
int32_t mili_key_file_unwrap(const uint8_t *file, size_t file_len,
                             uint8_t expected,
                             const uint8_t *password, size_t password_len,
                             uint8_t *out, size_t capacity, size_t *out_len);

/* Which kind of key a file holds, without a password. Authenticates nothing: any
 * bytes have a payload type at a fixed offset. For choosing which key to try. */
int32_t mili_key_file_payload_type(const uint8_t *file, size_t file_len, size_t *out);

/* SPEC.md section 12.1 rotation: a fresh salt, the same payload, the same password.
 * Changing a password is opening the key and wrapping it again. */
int32_t mili_key_file_rotate(const uint8_t *file, size_t file_len,
                             const uint8_t *password, size_t password_len,
                             uint8_t *out, size_t capacity, size_t *out_len);

/* Backups. `keys` is `key_count` entries, each `payload_type` followed by the key
 * bytes, and `keys_len` is `key_count` lengths. Two entries with the same identifier
 * are refused. */
int32_t mili_backup_create(const uint8_t *keys, const size_t *keys_len, size_t key_count,
                           const uint8_t *password, size_t password_len,
                           uint8_t *out, size_t capacity, size_t *out_len);

/* Writes back the entries concatenated, each one:
 *   0    16   key_id
 *   16   1    payload_type
 *   17   n    key bytes, 32, 64 or 32 by payload_type
 * An entry's length follows from its payload_type, so there is no length prefix and
 * the array is walked with the same sizes mili_backup_create takes. */
int32_t mili_backup_open(const uint8_t *backup, size_t backup_len,
                         const uint8_t *password, size_t password_len,
                         uint8_t *out, size_t capacity, size_t *out_len);

/* Reads what a backup container says about itself, without a password. Writes four
 * little endian uint32_t values in order: m_cost, t_cost, p_cost, entry_count, so
 * `out` must hold 16 bytes. No key material is read and no derivation runs, which is
 * the point: a tool can report what a file claims and what opening it would cost
 * before asking for a password. The header is unauthenticated, so this says what
 * the file claims rather than what it is. */
int32_t mili_backup_info(const uint8_t *backup, size_t backup_len,
                         uint8_t *out, size_t capacity);

/* Computes the 16 byte key identifier SPEC.md section 11 defines. `payload_type` is
 * MILI_PAYLOAD_SEALING, MILI_PAYLOAD_SIGNING or MILI_PAYLOAD_SYMMETRIC and `key` is
 * that many bytes, so the identifiers mili_backup_open returns can be compared
 * against what a caller computes for the key it holds. */
int32_t mili_key_id(uint8_t payload_type, const uint8_t *key, uint8_t *out);

#ifdef __cplusplus
}
#endif

#endif /* MILI_H */
